Repository eclipse-vertx/vert.x, pull requests merged in 2020-01, with the labels that each got.

#3226 CompletionStage interoperability
  src/main/asciidoc/index.adoc
  src/main/java/examples/CompletionStageInteropExamples.java
  src/main/java/io/vertx/core/Future.java
  src/main/java/io/vertx/core/impl/ContextImpl.java
  src/test/java/io/vertx/core/FutureTest.java
Labels: enhancement, major

#3223 Allow Shareable on JSON copy + Autocast getString()
  src/main/java/io/vertx/core/json/JsonArray.java
  src/main/java/io/vertx/core/json/JsonObject.java
  src/main/java/io/vertx/core/json/impl/JsonUtil.java
  src/test/java/io/vertx/core/json/JsonArrayTest.java
  src/test/java/io/vertx/core/json/JsonObjectTest.java
Labels: enhancement

#3264 Added test for worker starvation when lock concurrency is greater than worker pool size
  src/test/java/io/vertx/core/shareddata/AsynchronousLockTest.java
Labels: clustering
