Repository eclipse-vertx/vert.x, pull requests merged in 2021-11, with the labels that each got.

#4157 Several fixes necessary to implement WebSocket upgrade support in a reverse proxy implemented with Vert.x
  src/main/java/io/vertx/core/http/HttpServerRequest.java
  src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java
  src/main/java/io/vertx/core/http/impl/Http1xServerRequest.java
  src/main/java/io/vertx/core/http/impl/Http1xServerResponse.java
  src/main/java/io/vertx/core/http/impl/Http2ServerRequest.java
  src/main/java/io/vertx/core/http/impl/HttpUtils.java
  src/test/java/io/vertx/core/http/Http1xTest.java
  src/test/java/io/vertx/core/http/HttpTest.java
  src/test/java/io/vertx/core/http/WebSocketTest.java
Labels: bug, enhancement

#4159 HTTP/1.1 client metric is reset for allocated but non sent requests
  src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java
  src/test/java/io/vertx/core/http/Http1xMetricsTest.java
  src/test/java/io/vertx/test/fakemetrics/FakeHttpClientMetrics.java
Labels: bug

#4160 HTTP/1.1 client metric is reset for allocated but non sent requests - see #4158
  src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java
  src/test/java/io/vertx/core/http/Http1xMetricsTest.java
  src/test/java/io/vertx/test/fakemetrics/FakeHttpClientMetrics.java
Labels: bug

#4161 Do not close connection on http client request connect
  src/main/java/io/vertx/core/http/HttpClientRequest.java
  src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java
  src/main/java/io/vertx/core/http/impl/Http2ClientConnection.java
  src/main/java/io/vertx/core/http/impl/Http2UpgradedClientConnection.java
  src/main/java/io/vertx/core/http/impl/HttpClientRequestImpl.java
  src/main/java/io/vertx/core/http/impl/HttpClientResponseImpl.java
  src/main/java/io/vertx/core/http/impl/HttpClientStream.java
  src/test/java/io/vertx/core/http/Http1xTest.java
  src/test/java/io/vertx/core/http/HttpTest.java
Labels: bug

#4169 Fix #4168: Update manual to match code expectation
  src/main/asciidoc/filesystem.adoc
Labels: documentation

#4172 Tsegismont shared http client
  src/main/asciidoc/http.adoc
  src/main/generated/io/vertx/core/http/HttpClientOptionsConverter.java
  src/main/java/examples/HTTPExamples.java
  src/main/java/io/vertx/core/Vertx.java
  src/main/java/io/vertx/core/http/HttpClientOptions.java
  src/main/java/io/vertx/core/http/impl/HttpClientHolder.java
  src/main/java/io/vertx/core/http/impl/HttpClientImpl.java
  src/main/java/io/vertx/core/http/impl/SharedClientHttpStreamEndpoint.java
  src/main/java/io/vertx/core/http/impl/SharedHttpClient.java
  src/main/java/io/vertx/core/impl/VertxImpl.java
  src/test/java/io/vertx/core/http/Http1xTest.java
  src/test/java/io/vertx/core/http/SharedHttpClientTest.java
Labels: enhancement
