Repository eclipse-vertx/vert.x, pull requests merged in 2023-05, with the labels that each got.

#4683 Replace blocked thread tests log parsing by the blocked thread event handler
  src/main/java/io/vertx/core/impl/btc/BlockedThreadEvent.java
  src/test/java/io/vertx/core/BlockedThreadCheckerTest.java
  src/test/java/io/vertx/core/NamedWorkerPoolTest.java
  src/test/java/io/vertx/test/core/BlockedThreadWarning.java
Labels: enhancement

#4684 CompositeFuture methods should use generic Future<?> type instead of Future raw type
  src/main/java/examples/CoreExamples.java
  src/main/java/io/vertx/core/CompositeFuture.java
  src/main/java/io/vertx/core/eventbus/impl/EventBusImpl.java
  src/main/java/io/vertx/core/impl/DeploymentManager.java
  src/test/java/io/vertx/core/CompositeFutureTest.java
  src/test/java/io/vertx/core/ContextTest.java
  src/test/java/io/vertx/core/eventbus/CustomNodeSelectorTest.java
  src/test/java/io/vertx/core/http/Http1xTest.java
  src/test/java/io/vertx/core/shareddata/AsyncMapTest.java
  src/test/java/io/vertx/core/shareddata/AsynchronousLockTest.java
  src/test/java/io/vertx/core/spi/metrics/MetricsTest.java
  src/test/java/io/vertx/test/verticles/FaultToleranceVerticle.java
Labels: enhancement

#4691 Deprecate un-necessary streams
  src/main/asciidoc/streams.adoc
  src/main/java/io/vertx/core/TimeoutStream.java
  src/main/java/io/vertx/core/Vertx.java
  src/main/java/io/vertx/core/datagram/DatagramSocket.java
  src/main/java/io/vertx/core/http/HttpServer.java
  src/main/java/io/vertx/core/net/NetServer.java
Labels: deprecation

#4669 Fix missing headers bug when using clustered event bus
  src/main/java/io/vertx/core/eventbus/impl/clustered/ClusteredMessage.java
  src/test/java/io/vertx/core/eventbus/ClusteredEventBusTest.java
Labels: bug

#4694 Create SNI KeyManagerFactory in KeyCertOptions instead of SslContextProvider so it can be cached
  src/main/java/io/vertx/core/net/KeyCertOptions.java
  src/main/java/io/vertx/core/net/KeyManagerFactoryOptions.java
  src/main/java/io/vertx/core/net/KeyStoreOptionsBase.java
  src/main/java/io/vertx/core/net/PemKeyCertOptions.java
  src/main/java/io/vertx/core/net/impl/KeyStoreHelper.java
  src/main/java/io/vertx/core/net/impl/SSLHelper.java
  src/main/java/io/vertx/core/net/impl/SslContextProvider.java
Labels: enhancement

#4695 Create SNI KeyManagerFactory in KeyCertOptions instead of SslContextProvider so it can be cached
  src/main/java/io/vertx/core/net/KeyCertOptions.java
  src/main/java/io/vertx/core/net/KeyManagerFactoryOptions.java
  src/main/java/io/vertx/core/net/KeyStoreOptionsBase.java
  src/main/java/io/vertx/core/net/PemKeyCertOptions.java
  src/main/java/io/vertx/core/net/impl/KeyStoreHelper.java
  src/main/java/io/vertx/core/net/impl/SSLHelper.java
  src/main/java/io/vertx/core/net/impl/SslContextProvider.java
  src/test/java/io/vertx/core/http/HttpTLSTest.java
Labels: enhancement

#4704 Introduce generic version of CompositeFuture static methods
  src/main/asciidoc/futures.adoc
  src/main/java/examples/CoreExamples.java
  src/main/java/io/vertx/core/CompositeFuture.java
  src/main/java/io/vertx/core/Future.java
Labels: enhancement, deprecation
