Repository eclipse-vertx/vert.x, pull requests merged in 2023-02, with the labels that each got.

#4596 JsonParser should process fully the possible events when processing malformed input
  src/main/java/io/vertx/core/parsetools/impl/JsonParserImpl.java
  src/test/java/io/vertx/core/parsetools/JsonParserTest.java
Labels: bug

#4597 JsonParser should process fully the possible events when processing malformed input
  src/main/java/io/vertx/core/parsetools/impl/JsonParserImpl.java
  src/test/java/io/vertx/core/parsetools/JsonParserTest.java
Labels: bug

#4599 Blocked thread checker named worker threads leak
  src/main/java/io/vertx/core/impl/VertxImpl.java
  src/main/java/io/vertx/core/impl/VertxThread.java
  src/main/java/io/vertx/core/impl/btc/BlockedThreadChecker.java
  src/main/java/io/vertx/core/impl/btc/ThreadInfo.java
  src/test/java/io/vertx/core/ContextTest.java
  src/test/java/io/vertx/core/VertxTest.java
Labels: bug

#4600 Blocked thread checker named worker threads leak
  src/main/java/io/vertx/core/impl/VertxImpl.java
  src/main/java/io/vertx/core/impl/VertxThread.java
  src/main/java/io/vertx/core/impl/btc/BlockedThreadChecker.java
  src/main/java/io/vertx/core/impl/btc/ThreadInfo.java
  src/test/java/io/vertx/core/ContextTest.java
  src/test/java/io/vertx/core/VertxTest.java
Labels: bug

#4601 TCP server regression now accepts to bind to a port greater than 65535 and fail to report the failure.
  src/main/java/io/vertx/core/http/HttpServer.java
  src/main/java/io/vertx/core/http/impl/HttpServerImpl.java
  src/main/java/io/vertx/core/net/NetServer.java
  src/main/java/io/vertx/core/net/SocketAddress.java
  src/main/java/io/vertx/core/net/impl/NetServerImpl.java
  src/main/java/io/vertx/core/net/impl/SocketAddressImpl.java
  src/test/java/io/vertx/core/http/HttpTest.java
  src/test/java/io/vertx/core/net/NetTest.java
Labels: bug

#4602 TCP server regression now accepts to bind to a port greater than 65535 and fail to report the failure.
  src/main/java/io/vertx/core/http/HttpServer.java
  src/main/java/io/vertx/core/http/impl/HttpServerImpl.java
  src/main/java/io/vertx/core/net/NetServer.java
  src/main/java/io/vertx/core/net/SocketAddress.java
  src/main/java/io/vertx/core/net/impl/NetServerImpl.java
  src/main/java/io/vertx/core/net/impl/SocketAddressImpl.java
  src/test/java/io/vertx/core/http/HttpTest.java
  src/test/java/io/vertx/core/net/NetTest.java
Labels: bug

#4604 SSL improvements
  src/main/java/io/vertx/core/http/impl/Http1xServerConnection.java
  src/main/java/io/vertx/core/http/impl/Http1xUpgradeToH2CHandler.java
  src/main/java/io/vertx/core/http/impl/HttpServerImpl.java
  src/main/java/io/vertx/core/http/impl/HttpServerWorker.java
  src/main/java/io/vertx/core/net/impl/ChannelProvider.java
  src/main/java/io/vertx/core/net/impl/NetClientImpl.java
  src/main/java/io/vertx/core/net/impl/NetServerImpl.java
  src/main/java/io/vertx/core/net/impl/NetSocketImpl.java
  src/main/java/io/vertx/core/net/impl/SSLHelper.java
  src/main/java/io/vertx/core/net/impl/SslChannelProvider.java
  src/main/java/io/vertx/core/net/impl/SslContextProvider.java
  src/main/java/io/vertx/core/net/impl/TCPServerBase.java
  src/main/java/io/vertx/core/net/impl/VertxSniHandler.java
  src/test/java/io/vertx/core/http/HttpTLSTest.java
  src/test/java/io/vertx/core/net/SSLHelperTest.java
  src/test/java/io/vertx/it/SSLEngineTest.java
Labels: bug, enhancement

#4607 Fix SSLEngineOptions subclasses constructors not calling super
  src/main/java/io/vertx/core/net/JdkSSLEngineOptions.java
  src/main/java/io/vertx/core/net/OpenSSLEngineOptions.java
Labels: bug

#4633 HTTP client should rewrite the empty path to / for HTTP/2
  src/main/java/io/vertx/core/http/impl/Http2ServerRequest.java
  src/main/java/io/vertx/core/http/impl/HttpClientRequestBase.java
  src/main/java/io/vertx/core/http/impl/HttpClientRequestImpl.java
  src/main/java/io/vertx/core/http/impl/HttpRequestHead.java
  src/main/java/io/vertx/core/http/impl/HttpUtils.java
  src/test/java/io/vertx/core/http/HttpTest.java
Labels: bug

#4635 Optimise connection metrics reporting
  src/main/java/io/vertx/core/http/impl/Http1xConnectionBase.java
  src/main/java/io/vertx/core/net/impl/ConnectionBase.java
  src/main/java/io/vertx/core/net/impl/NetSocketImpl.java
Labels: enhancement

#4637 HTTP stream should not send a reset frame when the stream is closed
  src/main/java/io/vertx/core/http/impl/Http2ClientConnection.java
  src/main/java/io/vertx/core/http/impl/Http2ServerResponse.java
  src/main/java/io/vertx/core/http/impl/Http2ServerStream.java
  src/main/java/io/vertx/core/http/impl/VertxHttp2Stream.java
  src/test/java/io/vertx/core/http/Http2ClientTest.java
  src/test/java/io/vertx/core/http/Http2ServerTest.java
  src/test/java/io/vertx/core/http/HttpTest.java
Labels: bug

#4639 Vert.x HTTP h2c client gets an option to ensure client connection is always HTTP/2 when using h2c
  src/main/generated/io/vertx/core/http/HttpClientOptionsConverter.java
  src/main/java/io/vertx/core/http/HttpClientOptions.java
  src/main/java/io/vertx/core/http/impl/Http2UpgradeClientConnection.java
  src/main/java/io/vertx/core/http/impl/HttpChannelConnector.java
  src/test/java/io/vertx/core/http/Http2ClientTest.java
Labels: enhancement

#4640 HTTP/1.1 client connection API reset might lead corrupt the connection state
  src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java
  src/test/java/io/vertx/core/http/HttpTest.java
Labels: bug

#4632 Propagate trace when upgrading connections
  src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java
  src/main/java/io/vertx/core/http/impl/Http2ClientConnection.java
  src/main/java/io/vertx/core/http/impl/Http2UpgradeClientConnection.java
  src/main/java/io/vertx/core/http/impl/HttpClientStream.java
  src/test/java/io/vertx/core/spi/tracing/Http2TracerTest.java
  src/test/java/io/vertx/core/spi/tracing/HttpTracerTestBase.java
Labels: bug
