Repository eclipse-vertx/vert.x, pull requests merged in 2023-08, with the labels that each got.

#4784 Pool evict/acquire race fix
  src/main/java/io/vertx/core/net/impl/pool/CombinerExecutor.java
  src/main/java/io/vertx/core/net/impl/pool/SemaphoreExecutor.java
  src/main/java/io/vertx/core/net/impl/pool/SimpleConnectionPool.java
  src/main/java/io/vertx/core/net/impl/pool/Task.java
  src/test/java/io/vertx/core/net/impl/pool/ConnectionPoolTest.java
Labels: bug

#4799 Decouple the WebSocketBase frame aggregator from the frame handler
  src/main/java/io/vertx/core/http/impl/WebSocketImplBase.java
Labels: bug

#4802 HTTP/1.1 upgrade to H2C cannot process fully request entity with a size greater than the initial window size
  src/main/java/io/vertx/core/http/impl/VertxHttp2ConnectionHandler.java
  src/test/java/io/vertx/core/http/Http2WithUpgradeServerFileUploadTest.java
  src/test/java/io/vertx/core/http/HttpServerFileUploadTest.java
Labels: bug

#4803 HTTP/1.1 upgrade to H2C cannot process fully request entity with a size greater than the initial window size
  src/main/java/io/vertx/core/http/impl/VertxHttp2ConnectionHandler.java
  src/test/java/io/vertx/core/http/Http2WithUpgradeServerFileUploadTest.java
  src/test/java/io/vertx/core/http/HttpServerFileUploadTest.java
Labels: bug

#4804 Fix HTTP/1.1 server connection close header processing that close the connection too early
  src/main/java/io/vertx/core/http/impl/Http1xServerConnection.java
  src/main/java/io/vertx/core/http/impl/Http1xServerRequest.java
  src/main/java/io/vertx/core/http/impl/Http1xServerResponse.java
  src/main/java/io/vertx/core/http/impl/HttpUtils.java
  src/test/java/io/vertx/core/http/Http1xTest.java
Labels: bug

#4805 Fix HTTP/1.1 server connection close header processing that close the connection too early
  src/main/java/io/vertx/core/http/impl/Http1xServerConnection.java
  src/main/java/io/vertx/core/http/impl/Http1xServerRequest.java
  src/main/java/io/vertx/core/http/impl/Http1xServerResponse.java
  src/main/java/io/vertx/core/http/impl/HttpUtils.java
  src/test/java/io/vertx/core/http/Http1xTest.java
Labels: bug

#4807 Deprecate HttpServerResponse close method
  src/main/java/io/vertx/core/http/HttpServerResponse.java
Labels: deprecation

#4797 Buffer adding support for float le and double le
  src/main/java/io/vertx/core/buffer/Buffer.java
  src/main/java/io/vertx/core/buffer/impl/BufferImpl.java
  src/main/java/io/vertx/core/buffer/impl/BufferInternal.java
  src/test/java/io/vertx/core/buffer/BufferTest.java
  src/test/java/io/vertx/core/buffer/impl/VertxBufferTest.java
Labels: enhancement

#4816 HTTP2 timeout exception
  src/main/java/io/vertx/core/http/impl/HttpClientRequestBase.java
  src/main/java/io/vertx/core/http/impl/HttpClientRequestImpl.java
  src/test/java/io/vertx/core/http/HttpTest.java
Labels: enhancement

#4818 DnsClient can now be closed
  src/main/asciidoc/dns.adoc
  src/main/java/io/vertx/core/dns/DnsClient.java
  src/main/java/io/vertx/core/dns/impl/DnsClientImpl.java
  src/test/java/io/vertx/core/dns/DNSTest.java
  src/test/java/io/vertx/test/fakedns/FakeDNSServer.java
Labels: enhancement

#4820 Remove doc overrides
  src/main/asciidoc/buffers.adoc
  src/main/asciidoc/dns.adoc
  src/main/asciidoc/eventbus.adoc
  src/main/asciidoc/index.adoc
  src/main/asciidoc/json.adoc
  src/main/asciidoc/override/buffer_from_bytes.adoc
  src/main/asciidoc/override/configuring-eventbus.adoc
  src/main/asciidoc/override/configuring-native.adoc
  src/main/asciidoc/override/dependencies.adoc
  src/main/asciidoc/override/dns.adoc
  src/main/asciidoc/override/eventbus.adoc
  src/main/asciidoc/override/eventbus_headers.adoc
  src/main/asciidoc/override/hostname-resolution.adoc
  src/main/asciidoc/override/in-the-beginning.adoc
  src/main/asciidoc/override/verticle-configuration.adoc
  src/main/asciidoc/override/verticles.adoc
  src/main/java/docoverride/buffer/Examples.java
  src/main/java/docoverride/dns/Examples.java
  src/main/java/docoverride/eventbus/Examples.java
  src/main/java/examples/BufferExamples.java
  src/main/java/examples/DNSExamples.java
  src/main/java/examples/EventBusExamples.java
  src/main/java/examples/JsonExamples.java
Labels: documentation

#4827 Add Future eventually method with a supplier of future and deprecate the method with a function
  src/main/java/io/vertx/core/Future.java
  src/test/java/io/vertx/core/FutureTest.java
Labels: enhancement, deprecation

#4828 Replace Future eventually function argument by a supplier argument
  src/main/java/examples/FileSystemExamples.java
  src/main/java/io/vertx/core/Future.java
  src/main/java/io/vertx/core/http/impl/Http2ServerResponse.java
  src/main/java/io/vertx/core/http/impl/HttpNetSocket.java
  src/main/java/io/vertx/core/impl/DeploymentManager.java
  src/main/java/io/vertx/core/impl/future/Eventually.java
  src/main/java/io/vertx/core/impl/future/FutureBase.java
  src/test/java/io/vertx/core/FutureTest.java
  src/test/java/io/vertx/core/http/WebSocketTest.java
Labels: enhancement

#4795 Simplified API for locks
  src/main/asciidoc/shareddata.adoc
  src/main/java/examples/SharedDataExamples.java
  src/main/java/io/vertx/core/file/AsyncFile.java
  src/main/java/io/vertx/core/file/impl/AsyncFileImpl.java
  src/main/java/io/vertx/core/shareddata/SharedData.java
  src/main/java/io/vertx/core/shareddata/impl/SharedDataImpl.java
  src/test/java/io/vertx/core/file/FileSystemTest.java
  src/test/java/io/vertx/core/shareddata/AsynchronousLockTest.java
Labels: enhancement
